<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="celebraciones.aspx.cs" Inherits="prueba.celebraciones" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
     <fondo>
<p style="box-sizing: border-box; margin: 0px 0px 1em; padding: 0px; color: rgb(32, 32, 32); font-family: Montserrat; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Entre las costumbres m&aacute;s representativas que se destacan desde el inicio de las celebraciones, est&aacute;n:</p>
<p style="box-sizing: border-box; margin: 0px 0px 1em; padding: 0px; color: rgb(32, 32, 32); font-family: Montserrat; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: bold; line-height: 1;">Recorrido de La Antorcha Patria.&nbsp;</strong>Cada 13 de septiembre se realiza la entrega de la Antorcha de la Independencia entre Nicaragua y Costa Rica, donde el Gobierno del pa&iacute;s vecino hace entrega de la antorcha al Ministerio de Educaci&oacute;n P&uacute;blica de Costa Rica. Este recorrido lo realizan los estudiantes de las diferentes zonas del pa&iacute;s, que son elegidos previamente por sus centros educativos y, por lo general, son estudiantes destacados por sus calificaciones.&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 1em; padding: 0px; color: rgb(32, 32, 32); font-family: Montserrat; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br></p>
<figure class="wp-block-image size-large" style="box-sizing: border-box; display: block; margin: 0px 0px 1em; padding: 0px; color: rgb(32, 32, 32); font-family: Montserrat; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><img src = "data:image/png" srcset="https://www.presidencia.go.cr/bicentenario/wp-content/uploads/2021/09/4.jpg 649w, https://www.presidencia.go.cr/bicentenario/wp-content/uploads/2021/09/4-300x200.jpg 300w, https://www.presidencia.go.cr/bicentenario/wp-content/uploads/2021/09/4-370x247.jpg 370w, https://www.presidencia.go.cr/bicentenario/wp-content/uploads/2021/09/4-293x195.jpg 293w" sizes="(max-width: 649px) 100vw, 649px" style="box-sizing: border-box; max-width: 100%; height: auto; border: 0px;"></figure>
<p style="box-sizing: border-box; margin: 0px 0px 1em; padding: 0px; color: rgb(32, 32, 32); font-family: Montserrat; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Esta tradici&oacute;n de m&aacute;s de medio siglo comenz&oacute; a finales de la d&eacute;cada de los a&ntilde;os cincuenta como una iniciativa del profesor Alfredo Cruz Bola&ntilde;os, quien en ese entonces fung&iacute;a como supervisor de Educaci&oacute;n P&uacute;blica.</p>
<p style="box-sizing: border-box; margin: 0px 0px 1em; padding: 0px; color: rgb(32, 32, 32); font-family: Montserrat; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: bold; line-height: 1;">Desfile de faroles</strong>. Aunque la Independencia se conmemora el 15 de septiembre, las celebraciones se desarrollan a lo largo del mes. Una de ellas y quiz&aacute;s la m&aacute;s esperada por los ni&ntilde;os y ni&ntilde;as: el conocido desfile de faroles que se realiza cada 14 de septiembre en las noches.</p>
<p style="box-sizing: border-box; margin: 0px 0px 1em; padding: 0px; color: rgb(32, 32, 32); font-family: Montserrat; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">El desfile de faroles por lo general se realiza en los diferentes barrios de las comunidades. Los ni&ntilde;os (as) acompa&ntilde;ados por sus padres y maestros recorren las diferentes calles con sus faroles encendidos y se entona el Himno al 15 de septiembre cuando el reloj marca las 6 p.m.&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 1em; padding: 0px; color: rgb(32, 32, 32); font-family: Montserrat; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&ldquo;En Costa Rica, la tradici&oacute;n del desfile de faroles inici&oacute; en 1953, cuando despu&eacute;s de la Revoluci&oacute;n de 1948, se da una especial importancia al rescate de los valores patrios, por lo que el profesor V&iacute;ctor Manuel Ure&ntilde;a Arguedas (1912-1995), director Provincial de Escuelas de San Jos&eacute;, con el objetivo de inculcar en el pueblo el esp&iacute;ritu c&iacute;vico, empezando con los ni&ntilde;os (as). Ure&ntilde;a organiz&oacute; oficialmente el desfile de faroles y encomend&oacute; a los maestros y profesores de las escuelas y colegios, realizar esta actividad todos los a&ntilde;os el 14 de septiembre, a las 6 p.m.</p>
<p style="box-sizing: border-box; margin: 0px 0px 1em; padding: 0px; color: rgb(32, 32, 32); font-family: Montserrat; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&ldquo;Seg&uacute;n las fuentes, este primer desfile, tuvo una grand&iacute;sima participaci&oacute;n de ni&ntilde;os (as) de las escuelas josefinas, quienes acompa&ntilde;ados de sus maestros y padres y alzando art&iacute;sticos faroles desfilaron por las calles de San Jos&eacute; llenando la capital de alegr&iacute;a y fervor c&iacute;vico&rdquo;, explic&oacute; Sonia G&oacute;mez, historiadora del Centro de Investigaci&oacute;n y Conservaci&oacute;n del Patrimonio Cultural.</p>
<p style="box-sizing: border-box; margin: 0px 0px 1em; padding: 0px; color: rgb(32, 32, 32); font-family: Montserrat; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Partitura del Himno Patri&oacute;tico al 15 de septiembre:&nbsp;<a href="https://bit.ly/3DvYg9K" style="box-sizing: border-box; color: rgb(51, 51, 51); text-decoration: none; transition: all 0.3s ease 0s;">https://bit.ly/3DvYg9K</a></p>
<p style="box-sizing: border-box; margin: 0px 0px 1em; padding: 0px; color: rgb(32, 32, 32); font-family: Montserrat; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: bold; line-height: 1;">El desfile de estudiantes.&nbsp;</strong>Otra de las m&aacute;s esperadas tradiciones es el desfile de estudiantes por las principales calles y avenidas a lo largo y ancho del pa&iacute;s.</p>
<p style="box-sizing: border-box; margin: 0px 0px 1em; padding: 0px; color: rgb(32, 32, 32); font-family: Montserrat; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Costa Rica no tiene ej&eacute;rcito, raz&oacute;n por la cual quienes desfilan son el ej&eacute;rcito de ni&ntilde;os (as) y adolescentes, que con tambores, liras, flautas y mucho fervor patrio desfilan al ritmo de canciones tradicionales costarricenses por las diferentes zonas del pa&iacute;s. En algunas ocasiones estos desfiles se acompa&ntilde;an de mascaradas y marimbas, as&iacute; como j&oacute;venes vestidas con los atuendos patrios, quienes realizan los bailes t&iacute;picos de Costa Rica.&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 1em; padding: 0px; color: rgb(32, 32, 32); font-family: Montserrat; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&ldquo;(&hellip;) se abre lugar a que reluzcan los colores blanco, azul y rojo. Veremos &laquo;mascaradas&raquo;, cimarronas con m&uacute;sica a todo volumen, los ni&ntilde;os (as) y adolescentes bailando en l&iacute;neas y al&nbsp;comp&aacute;s de los tambores&nbsp;de las bandas con sus trajes t&iacute;picos y de gala. Desde meses antes podemos escuchar los tambores de las bandas que practican en las escuelas. Ser&aacute; un gran d&iacute;a para ellos donde mostraran sus mejores interpretaciones&nbsp;y rendimiento&rdquo;. (Fuente:&nbsp;<a href="https://si.cultura.cr/" style="box-sizing: border-box; color: rgb(51, 51, 51); text-decoration: none; transition: all 0.3s ease 0s;">https://si.cultura.cr</a>)</p>
<p style="box-sizing: border-box; margin: 0px 0px 1em; padding: 0px; color: rgb(32, 32, 32); font-family: Montserrat; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: bold; line-height: 1;">Decoraci&oacute;n de casas e instituciones.&nbsp;</strong>Otra manifestaci&oacute;n cultural enmarcada en la celebraci&oacute;n de las fiestas patrias es decorar las casas y las instituciones con s&iacute;mbolos patrios, banderas y colores que representan la Bandera Nacional de Costa Rica.</p>  
</fondo>
</body>
</html>
