<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="simbolos.aspx.cs" Inherits="prueba.simbolos" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
   <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans:600'><link rel="stylesheet" href="css/simbolos.css">
        <title>Simbolos</title>
</head>
     <div id="fondo">
   <img src="http://costarica-simbolosnacionales.weebly.com/uploads/2/4/5/1/24510341/9452900_orig.png">
  </img>
</div>
<body>
     <fondo>
  <p style="box-sizing: inherit; margin: 0px 0px 15px; padding: 0px; color: rgb(10, 10, 10); font-family: Roboto, sans-serif; font-size: 17.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">El 15 de setiembre del pr&oacute;ximo a&ntilde;o se celebrar&aacute; pon bombos y platillos la Independencia declarada en Guatemala, que fue el detonante para que El Salvador declarara la suya el 21 de setiembre, al recibir la noticia de los sucesos de Guatemala, Nicaragua y Honduras lo hicieron el 28 de setiembre, y Nicaragua reafirm&oacute; corrigiendo su declaratoria del 28 de setiembre el 12 de octubre, y Costa Rica conociendo lo sucedido en Guatemala y en Nicaragua, que nos llegaron las Actas de esos dos pa&iacute;ses, tanto a San Jos&eacute; como a Cartago, a mediados de octubre, se decidi&oacute; convocar a delegados de los pueblos para que se reunieran en Cartago y el 29 de octubre de 1821 definieran la situaci&oacute;n de Costa Rica, tom&aacute;ndose en Cartago la decisi&oacute;n de Declarar la Independencia de Costa Rica, el 29 de octubre de 1821.</p>
<p style="box-sizing: inherit; margin: 0px 0px 15px; padding: 0px; color: rgb(10, 10, 10); font-family: Roboto, sans-serif; font-size: 17.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">As&iacute;, ante el Bicentenario de la Independencia, tenemos dos fechas a celebrar, el 15 de setiembre y el 29 de octubre. &iquest;Los actos que se tienen pensados para esta celebraci&oacute;n comprender&aacute;n estas dos fechas, o se mantendr&aacute;n en t&eacute;rminos oficiales, de Gobierno, en los actos centroamericanos que girar&aacute;n alrededor del 15 de setiembre? Hasta hoy la celebraci&oacute;n de la Independencia no se conmemora el 29 de octubre. Esta es una fecha pr&aacute;cticamente omitida en el calendario de fechas patrias.</p>
<p style="box-sizing: inherit; margin: 0px 0px 15px; padding: 0px; color: rgb(10, 10, 10); font-family: Roboto, sans-serif; font-size: 17.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Que los actos que se celebran el 15 de setiembre de cada a&ntilde;o terminen en la ciudad de Cartago no significa nada respecto a la determinaci&oacute;n tomada en esa ciudad el 29 de octubre de 1821.</p>
<p style="box-sizing: inherit; margin: 0px 0px 15px; padding: 0px; color: rgb(10, 10, 10); font-family: Roboto, sans-serif; font-size: 17.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Pero, ante el Bicentenario, obligatoriamente deben tenerse las dos fechas y los dos escenarios. La Municipalidad de Cartago, y el nuevo Alcalde, Mario Redondo, no pueden estar al margen de esta celebraci&oacute;n.</p>
<p style="box-sizing: inherit; margin: 0px 0px 15px; padding: 0px; color: rgb(10, 10, 10); font-family: Roboto, sans-serif; font-size: 17.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">El 29 de octubre del 2021 tiene que realizarse un gran acto conmemorativo en Cartago, de la Declaraci&oacute;n de Independencia de Costa Rica, quiz&aacute; el m&aacute;s importante de los que puedan celebrarse. De hecho desde el 15 de setiembre hasta el 29 de octubre deber&iacute;an hacerse actividades en todo el territorio nacional, relacionadas con esta celebraci&oacute;n. Incluso en cada uno de los pueblos, Alajuela, Heredia, San Jos&eacute;, Cartago, Ujarraz, Barva, Bagaces, donde se nombraron delegados para que en Cartago definieran el destino y el futuro de Costa Rica.</p>
<p style="box-sizing: inherit; margin: 0px 0px 15px; padding: 0px; color: rgb(10, 10, 10); font-family: Roboto, sans-serif; font-size: 17.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">En cada uno de estos pueblos o ciudades igualmente deben realizarse actos conmemorativos, de car&aacute;cter regional, que exalten su situaci&oacute;n en 1821 y particularmente se distingan a los representantes de cada pueblo, en la Reuni&oacute;n de Cartago el 29 de octubre, quienes firmaron el Acta de Independencia del 29 de octubre de 1821.</p>
<p style="box-sizing: inherit; margin: 0px 0px 15px; padding: 0px; color: rgb(10, 10, 10); font-family: Roboto, sans-serif; font-size: 17.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">No conozco la hoja de ruta de esta celebraci&oacute;n, de los actos oficiales, y del sistema de Educaci&oacute;n P&uacute;blica, que desde ahora ya debe estar definida, con detalles. Deber&iacute;a ponerse en conocimiento p&uacute;blico para que a su alrededor se vaya armando el entramado con todos los sectores de la sociedad para esta Magna Celebraci&oacute;n, y para que la celebraci&oacute;n del Bicentenario de la Independencia no se concentre en los d&iacute;as inmediatos al 15 de setiembre.</p>
<p style="box-sizing: inherit; margin: 0px 0px 15px; padding: 0px; color: rgb(10, 10, 10); font-family: Roboto, sans-serif; font-size: 17.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Este Gobierno se autodenomin&oacute; el Gobierno del Bicentenario, y parte de su papeler&iacute;a oficial as&iacute; lo consigna, pero que se est&aacute; haciendo con direcci&oacute;n a esa fecha, desde ahora. La celebraci&oacute;n del Bicentenario deber&iacute;a comprender una serie de actos, de distinto tipo, continuos desde este a&ntilde;o hasta el pr&oacute;ximo.</p>
<p style="box-sizing: inherit; margin: 0px 0px 15px; padding: 0px; color: rgb(10, 10, 10); font-family: Roboto, sans-serif; font-size: 17.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">La Biblioteca Nacional, por su propia iniciativa, bajo el impulso y la conducci&oacute;n de su Directora, Laura Rodr&iacute;guez, ha empezado a celebrar este acontecimiento en un conjunto de actividades, tipo conferencias, que se proyectar&aacute;n desde el martes 3 de marzo hasta el pr&oacute;ximo a&ntilde;o, con actividades mensuales, que se van ir incrementando.</p>
<p style="box-sizing: inherit; margin: 0px 0px 15px; padding: 0px; color: rgb(10, 10, 10); font-family: Roboto, sans-serif; font-size: 17.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Obviamente las Escuelas de Historia y de Estudios Sociales de las Universidades Estatales, los Centros acad&eacute;micos de Investigaci&oacute;n Hist&oacute;rica har&aacute;n lo propio. &iquest;Las Universidades privadas que preparan profesores en el campo de los Estudios Sociales est&aacute;n prepar&aacute;ndose, y tienen actividades acad&eacute;micas programadas para este acontecimiento? &iquest;El Consejo Superior de Educaci&oacute;n tiene una hoja de ruta desde ahora hasta el pr&oacute;ximo a&ntilde;o?</p>
<p style="box-sizing: inherit; margin: 0px 0px 15px; padding: 0px; color: rgb(10, 10, 10); font-family: Roboto, sans-serif; font-size: 17.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Y, la celebraci&oacute;n del Bicentenario de la Independencia, con esas fechas del 15 de setiembre y 29 de octubre del pr&oacute;ximo a&ntilde;os, se acaba en ellas? &iquest;Se debe prorrogar la celebraci&oacute;n hasta la Guerra de Ochomogo de 1823, dentro de la perspectiva del Gobierno del Bicentenario? &iquest;O se debe llevar la celebraci&oacute;n hasta la proclamaci&oacute;n del Estado de Costa Rica, y la designaci&oacute;n del Primer Jefe de Estado, Juan Mora Fern&aacute;ndez, dentro de la Rep&uacute;blica Federal?</p>
<p style="box-sizing: inherit; margin: 0px 0px 15px; padding: 0px; color: rgb(10, 10, 10); font-family: Roboto, sans-serif; font-size: 17.6px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Y, alrededor de las fechas de Independencia, del 15 de setiembre y del 29 de octubre, podr&iacute;an discutirse, como algunos historiadores han sugerido, otras fechas, a modo de la celebraci&oacute;n relacionadas con la Independencia, la del 1 de diciembre de 1821, cuando se aprob&oacute; la Primera Constituci&oacute;n del pa&iacute;s, la de &ldquo;Pacto Social Fundamental o Pacto de Concordia&rdquo;, la de instalaci&oacute;n de la Primera Junta de Legados, cuando se integr&oacute; el Primer Gobierno en vida independiente, o la misma de la Guerra de Ochomogo.</p>
    </fondo>
</body>
</html>
